### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by santhoshkumarv85** [ExaVault/evapi-php#5]
Should i need SSL to integrate your API?
Exception when calling AuthenticationApi->authenticateUser: API call to https://api.exavault.com/v1/authenticateUser failed: SSL certificate problem: unable to get local issuer certificate

**Comment by dordal** [comment]
@santhoshkumarv85 yes, our API is only available via SSL. However, that's the case with most APIs, and the error you're talking about sounds like you're unable to verify our root certificate. It is likely you are on an older operating system that doesn't have our third-party root certificate installed. You can download it from Comodo here: 

[https://support.comodo.com/index.php?/Knowledgebase/Article/View/945/0/root-addtrust-external-ca-root](https://support.comodo.com/index.php?/Knowledgebase/Article/View/945/0/root-addtrust-external-ca-root)

The mechanism of trusting it varies by OS, but Google 'trust third party root certificate OSNAME' (e.g. 'trust third party root certificate ubuntu') and you should find instructions for your OS.
